### PR TITLE
upgrade examples for 2021 TS

### PR DESCRIPTION
**Pull request by jmecosta**

### CODE REVIEW

**Comment by CarlosHerrero** [comment]
I don't understand the diff. Why are .cpp and .inp files touched/moved?
Was this change supposed to mean changes only in the project files?

**Comment by jmecosta** [comment]
Cpp files are touched, because they didn't compile with nee compilers

**Comment by CarlosHerrero** [comment]
OK, but the "Files chaged (44)" just shows a lot of files all text in green. It is not possible to do a review that way. Maybe you can tell Jukka what was actually changed in those files, he knows dev-kit functions and tools.

**Comment by jmecosta** [comment]
there was nothing really touched at source level, there was a initialization of a var
image

and a pragma warning disable...

nothing functionally broken... but anyway, would be good if you could get the solution and copile it locally see if everyting is in place

**Pull request merged**
